version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flowers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flower_network

  backend:
    build:
      context: ./flower-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./flower-backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flowers
    depends_on:
      - db
    networks:
      - flower_network

  frontend:
    build:
      context: ./flower-front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./flower-front:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - flower_network

volumes:
  postgres_data:

networks:
  flower_network:
    driver: bridge

